plugins {
    id 'java'
    id 'pmd'
    id 'jacoco'
}

group = 'hu.therealuhlarzoltan.framestowatch'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

pmd {
    consoleOutput = true
}

tasks.named("pmdMain") {
    ruleSetFiles = files("$rootDir/config/pmd/pmd-main.xml")
}

tasks.named("pmdTest") {
    ruleSetFiles = files("$rootDir/config/pmd/pmd-test.xml")
}

jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = 0.80
            }
        }
    }
}

check.dependsOn jacocoTestCoverageVerification